title: Jayashree Balaraman
author: GitHub User
email: jbalaraman@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the world of Jayashree Balaraman.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot
