theme: minima
title: Jayashree Balaraman
author: jbalaraman1
email: jbalaraman@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 My name is Jayashree Balaraman. This website is a little about me. 

# social links
instagram_username: shree_balaram # DO NOT include the @ character, or else the build will fail!
github_username:  jbalaraman1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
